### ISSUE TITLE
require('when/node') fails as node is both a .js file and folder

### ISSUE THREAD

**Issue by paulgoldsmith** [doctorrustynelson/yearn#90]
The npm module [when](https://www.npmjs.com/package/when) has a folder `node` and file `node.js`. If the following is executed

```
ynode> require('when/node');
```

An uncaught exception is thrown as it attempts to yearn the folder instead of the file.

A real world example of this case is the npm module [phridge](https://www.npmjs.com/package/phridge) which does this very require in [spawn.js](https://github.com/peerigon/phridge/blob/master/lib/spawn.js#L3).

**Comment by doctorrustynelson** [comment]
The issue is really only occurring when running with legacy turned on and that's due to a different bug that will be addressed.
